
String getHtml() 
{
  String html = "";
  html += "<html>";
  html += "    <head>";
  html += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">";
  html += "        <title>Spark-Fi</title>";
  html += "        <link rel=\"stylesheet\" href=\"https://bootswatch.com/4/darkly/bootstrap.min.css\">";
  html += "        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.0.9/css/all.css\" integrity=\"sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1\" crossorigin=\"anonymous\">";
  html += "        <style>";
  html += "            li {";
  html += "                float: left;";
  html += "                padding-right: 1em;";
  html += "                padding-top: 1em;";
  html += "            }";
  html += "            .row {";
  html += "                margin-bottom: 3em;";
  html += "            }";
  html += "            .btn-xl {";
  html += "                padding: 18px 28px;";
  html += "                font-size: 1.5em; ";
  html += "                line-height: normal;";
  html += "                -webkit-border-radius: 8px;";
  html += "                -moz-border-radius: 8px;";
  html += "                        border-radius: 8px;";
  html += "            }";
  html += "        </style>";
  html += "    </head>";
  html += "    <body>";
  html += "        <div class=\"jumbotron\">";
  html += "            <div class=\"container justify-content-center text-center\">";
  html += "                <h1 class=\"text-danger display-1\">SparkFi</h1>";
  html += "            </div>";
  html += "        </div>";
  html += "        <div class=\"container\">";
  html += "            <div class=\"row\">";
  html += "                <div class=\"col justify-content-center text-center\">";
  html += "                    <h2>Channels</h2>";
  html += "                    <ul style=\"list-style-type: none;\">";
  html += "                        <li><button type=\"button\" data-value=\"1\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 1</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"2\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 2</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"3\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 3</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"4\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 4</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"5\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 5</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"6\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 6</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"7\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 7</button></li>";
  html += "                        <li><button type=\"button\" data-value=\"8\" class=\"btn channel btn-outline-danger\"><i class=\"fas fa-fire\"></i>&nbsp;Channel 8</button></li>";
  html += "                    </ul>";
  html += "                </div>";
  html += "                <div class=\"col justify-content-center text-center\">";
  html += "                    <h2>Ignition Duration</h2>                ";
  html += "                    <div class=\"form-group\">";
  html += "                        <label for=\"example-text-input\" class=\"col-2 col-form-label\">Duration</label>";
  html += "                        <div class=\"\">";
  html += "                            <input class=\"form-control\" type=\"number\" value=\"2000\" id=\"ignition-duration\" />";
  html += "                        </div>";
  html += "                    </div>";
  html += "                </div>";
  html += "            </div>";
  html += "            <div class=\"row\">";
  html += "                <div class=\"col justify-content-center text-center\">";
  html += "                    <button id=\"spark-button\" class=\"btn btn-danger btn-xl\" role=\"button\" aria-pressed=\"true\">Spark</button>";
  html += "                </div>";
  html += "            </div>";
  html += "            <hr>";
  html += "            <footer>";
  html += "                <p>&copy; TheBentern 2018</p>";
  html += "            </footer>";
  html += "        </div>";
  html += "        <div class=\"modal fade\" id=\"modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">";
  html += "            <div class=\"modal-dialog\" role=\"document\">";
  html += "                <div class=\"modal-content\">";
  html += "                    <div class=\"modal-body\"></div>";
  html += "                    <div class=\"container-fluid\">";
  html += "                        <div class=\"row\">";
  html += "                            <div class=\"col justify-content-center text-center\">";
  html += "                                <h3>Igniting channels</h3>";
  html += "                                <h3 id=\"ignited-channels\"></h3>";
  html += "                                <br />";
  html += "                                <div class=\"fa-3x\">";
  html += "                                    <i class=\"text-danger fas fa-spinner fa-spin\"></i>";
  html += "                                </div>";
  html += "                            </div>";
  html += "                        </div>";
  html += "                    </div>";
  html += "                </div>";
  html += "            </div>";
  html += "        </div>";
  html += "        <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>";
  html += "        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>";
  html += "        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>";
  html += "        <script type=\"text/javascript\">";
  html += "            $(document).on('click', 'button.channel', toggleChannelActive);";
  html += "            $(document).on('click', '#spark-button', sparkClick);";
  html += "            ";
  html += "            function sparkClick (e) {";
  html += "                e.preventDefault();";
  html += "                $('#ignited-channels').empty();";
  html += "                var channels = $('button.channel.active')";
  html += "                    .map(function(index, item) { return $(item).data('value').toString() })";
  html += "                    .toArray();";
  html += "                var duration = $('#ignition-duration').val();";
  html += "";
  html += "                $('#ignited-channels').text(channels.join(', '));";
  html += "                postSpark(channels, duration);";
  html += "                $('#modal').modal();";
  html += "                setTimeout(function() { $('#modal').modal('hide') }, duration);";
  html += "            }";
  html += "";
  html += "            function toggleChannelActive (e) {";
  html += "                e.preventDefault();";
  html += "                $(this).toggleClass('active');";
  html += "            }";
  html += "";
  html += "            function postSpark(channels, duration) {";
  html += "                var xhr = new XMLHttpRequest();";
  html += "                xhr.open('post', '/spark');";
  html += "                xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');";
  html += "                xhr.send('channel=' + channels.join('&channel=') + '&duration=' + duration);";
  html += "            }";
  html += "        </script>";
  html += "    </body>";
  html += "</html>";
  html += "";
  return html;
}
  